config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :products
  resources :stores
  resources :store_products
  resources :locate_stores do
    collection do
      post 'search'
    end  
  end

  root 'locate_stores#index'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :stores 
      resources :products
   end
 end

end

app/models/store.rb
class Store < ActiveRecord::Base
  require 'open-uri'
  require 'json'
  has_many :store_products
  has_many :products, through: :store_products
  
  # CReate seeds from Tesco STore API
  def self.create_seeds_using_stores_api
    #{lat: 51.508530, lng: -0.076132}
    long = -0.076132
    lat = 51.508530
    store_API_results = JSON.parse(open("http://api.tescolabs.com/api/stores/#{long},#{lat}").read)
    store_API_results["results"].each {|f| 
      p "Store.create(name: " +"'"+ f["obj"]["placeName"].to_s + "'," + "address:" + "'" + f["obj"]["placeName"].concat(f["obj"]["_id"]).to_s+ "'," + "lat:" + "'" + f["obj"]["lat"].to_s + "'," + "long:" + "'" + f["obj"]["lng"].to_s + "'," + "location_id:" + "'" +  f["obj"]["_id"].to_s+ "'," + "store_distance:" + "'" + f["dis"].to_s+ "'," + "store_type:" + "'" +f["obj"]["typ"].to_s+ "'"")"
    }
   # return store_API
    # store_API will store list of 5 nearest TESCO stores
    # send list of product ids and the store_API result to devu API.
  end
  
  


  def self.get_near_stores(lat,lang)
  end

  def self.max_prod_avail(product_ids)
    found_stores = []
    stores = Store.all
    stores.each do |store|
      response = Product.search_availability(store.id,product_ids)
      found_stores << {store: store.id,count: response[:count], distance: store.store_distance, lat: store.lat, lng: store.long, store_name: store.name,
       address: store.address, store_distance: store.store_distance, store_type: store.store_type  } if response[:count] > 0
     end
    # store_by_count = found_stores.sort_by { |store| store[:count] }.last
    # store_by_distance = found_stores.select{|store| store[:count] == store_by_count[:count]}.sort_by{|dis| dis[:distance]}.first[:store]
    return found_stores
  end

end

app/controllers/api/v1/stores_controller.rb
module Api
  module V1
    class StoresController < ApplicationController
      respond_to :json

      def index
        if params[:store_id] and params[:product_ids]
          respond_with Product.search_availability(params[:store_id],params[:product_ids])
        else
         render json: { :status => :error, :message => "store_id or product_ids are missing" }
       end
       
     end

     def product_avail
      if params[:product_ids] 
        respond_with Store.max_prod_avail(params[:product_ids])
      else
       render json: { :status => :error, :message => "product_ids are missing" }
     end
   end

 end
end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :lat, :long, :pin, :phone, :store_distance)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => "form-horizontal store" } do |f| %>

    <% if @store.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @store.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:address]) %>
  </div>
  <div class="control-group">
    <%= f.label :lat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:lat]) %>
  </div>
  <div class="control-group">
    <%= f.label :long, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :long, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:long]) %>
  </div>
   <div class="control-group">
    <%= f.label :store_distance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_distance, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:store_distance]) %>
  </div>
  <div class="control-group">
    <%= f.label :pin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pin, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:pin]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :location_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location_id, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:location_id]) %>
  </div>
    <div class="control-group">
    <%= f.label :store_distance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_distance, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:store_distance]) %>
  </div>
  <div class="control-group">
    <%= f.label :store_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_type, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:store_type]) %>
  </div>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            stores_path, :class => 'btn btn-default' %>

<% end %>

app/views/stores/edit.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/index.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:lat) %></th>
      <th><%= model_class.human_attribute_name(:long) %></th>
      <th><%= model_class.human_attribute_name(:pin) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:location_id)%></th>
      <th><%= model_class.human_attribute_name(:store_distance)%></th>
      <th><%= model_class.human_attribute_name(:store_type)%></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.id, store_path(store) %></td>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.lat %></td>
        <td><%= store.long %></td>
        <td><%= store.pin %></td>
        <td><%= store.phone %></td>
        <td><%= store.location_id %></td>
        <td><%= store.store_distance %></td>
        <td><%= store.store_type %></td>
        <td><%=l store.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_path(store), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_path(store),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_store_path,
            :class => 'btn btn-primary' %>

app/views/stores/new.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/show.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @store.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @store.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lat) %>:</strong></dt>
  <dd><%= @store.lat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:long) %>:</strong></dt>
  <dd><%= @store.long %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pin) %>:</strong></dt>
  <dd><%= @store.pin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @store.phone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              stores_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_path(@store), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_path(@store),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>