config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :products
  resources :stores
  resources :store_products
  resources :locate_stores do
    collection do
      post 'search'
    end  
  end

  root 'locate_stores#index'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :stores 
      resources :products
   end
 end

end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :store
end

app/controllers/store_products_controller.rb
class StoreProductsController < ApplicationController

  def index
    @store_products = StoreProduct.includes(:store).includes(:product)
  end

  def new
    @store_product = StoreProduct.new
    @products = Product.all
    @stores = Store.all
  end

  def create
    @store_product = StoreProduct.new(store_product_params)

    respond_to do |format|
      if @store_product.save
        format.html { redirect_to store_products_path, notice: 'Store was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

    # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
   @store = StoreProduct.find(params[:id])
   @store.destroy
   respond_to do |format|
    format.html { redirect_to store_products_url, notice: 'Store was successfully destroyed.' }
    format.json { head :no_content }
  end
end
  private

  def store_product_params
    params.require(:store_product).permit(:quantity, :product_id, :store_id, :quantity, :available)
  end

end

app/helpers/store_products_helper.rb
module StoreProductsHelper
end

app/views/store_products/_form.html.erb
<%= form_for @store_product, :html => { :class => "form-horizontal store_product" } do |f| %>

    <% if @store_product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@store_product.errors.count, "error") %> prohibited this store_product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @store_product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :product_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :product_id, (@products.collect{|p| [p.name, p.id]}) , :class => 'form-control' %>
    </div>
    <%= error_span(@store_product[:product_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :store_id, (@stores.collect{|s| [s.name, s.id]}) ,:class => 'form-control' %>
    </div>
    <%= error_span(@store_product[:store_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :quantity, :class => 'form-control' %>
    </div>
    <%= error_span(@store_product[:quantity]) %>
  </div>
  <div class="control-group">
    <%= f.label :available, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :available, ['true', 'false'], :class => 'form-control' %>
    </div>
    <%= error_span(@store_product[:available]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            store_products_path, :class => 'btn btn-default' %>

<% end %>

app/views/store_products/edit.html.erb
<%- model_class = StoreProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/store_products/index.html.erb
<%- model_class = StoreProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:available) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @store_products.each do |store_product| %>
      <tr>
        <td><%= link_to store_product.id, store_product_path(store_product) %></td>
        <td><%= store_product.product.name %></td>
        <td><%= store_product.store.name%></td>
        <td><%= store_product.quantity %></td>
        <td><%= store_product.available %></td>
        <td><%=l store_product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_product_path(store_product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_product_path(store_product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_store_product_path,
            :class => 'btn btn-primary' %>

app/views/store_products/new.html.erb
<%- model_class = StoreProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/store_products/show.html.erb
<%- model_class = StoreProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @store_product.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_id) %>:</strong></dt>
  <dd><%= @store_product.store_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @store_product.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:available) %>:</strong></dt>
  <dd><%= @store_product.available %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              store_products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_product_path(@store_product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_product_path(@store_product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>