config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :products
  resources :stores
  resources :store_products
  resources :locate_stores do
    collection do
      post 'search'
    end  
  end

  root 'locate_stores#index'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :stores 
      resources :products
   end
 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "My Store Locator" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
    </head>
    <body>

      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">My Store Locator</a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%#= link_to "Stores", stores_path  %></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <footer>
          <p> Tesco Hackathon 2015 </p>
        </footer>

      </div> <!-- /container -->

    </body>
    </html>